# Generated by Django 3.0.8 on 2021-01-15 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='guid_resources',
            field=models.ForeignKey(db_column='guid_resources', null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Resources'),
        ),
        migrations.AlterField(
            model_name='takenparams',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
