# Generated by Django 3.1.14 on 2026-07-27 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210115_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgroups80020meters',
            name='measuringpoint_code',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(help_text='Уникальный номер отчёта (91, 102, 152 и т.д.)', unique=True, verbose_name='Номер отчёта')),
                ('name', models.CharField(help_text='Краткое описание отчёта', max_length=200, verbose_name='Название отчёта')),
                ('show_lic_num', models.BooleanField(default=False, help_text='Актуально для 91, 102, 104, 106 и старше', verbose_name='Показывать лицевой номер')),
                ('separator', models.CharField(choices=[(',', 'Запятая (123,45)'), ('.', 'Точка (123.45)'), (' ', 'Пробел (123 45)'), ('', 'Без разделителя')], default=',', max_length=5, verbose_name='Разделитель')),
                ('round_size', models.PositiveSmallIntegerField(default=3, verbose_name='Знаков после запятой')),
                ('comment_to_excel', models.BooleanField(default=False, help_text='Для отчётов 114, 58, 56', verbose_name='Выводить комментарии в Excel')),
                ('show_stoyak', models.BooleanField(default=True, help_text='Для отчётов 152, 157, 158', verbose_name='Показывать стояк')),
                ('show_floors', models.BooleanField(default=True, help_text='Для отчётов 152, 144', verbose_name='Показывать этаж')),
                ('num_is_string', models.BooleanField(default=False, help_text='Выводить ли числа в отчёты как строку', verbose_name='Числа как строки')),
                ('null_field', models.CharField(default='Н/Д', help_text='Что выводить, если данные не считались с прибора', max_length=20, verbose_name='Обозначение отсутствующих данных')),
                ('order_fields', models.CharField(blank=True, default='', help_text='Поля через запятую, например: flat_number,name', max_length=200, verbose_name='Поля сортировки')),
                ('order_direction', models.CharField(choices=[('asc', 'По возрастанию'), ('desc', 'По убыванию')], default='asc', max_length=4, verbose_name='Направление сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отключите, если отчёт больше не используется', verbose_name='Активен')),
                ('guid_resources', models.ForeignKey(db_column='guid_resources', help_text='К какому ресурсу относится отчёт', on_delete=django.db.models.deletion.CASCADE, to='general.resources', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Настройка отчёта',
                'verbose_name_plural': 'Настройки отчётов',
                'db_table': 'report_configs',
                'ordering': ['number'],
            },
        ),
    ]
