# Generated by Django 3.1.14 on 2026-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20260727_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='separator',
            field=models.CharField(choices=[(',', 'Запятая (123,45)'), ('.', 'Точка (123.45)')], default=',', max_length=5, verbose_name='Разделитель'),
        ),
    ]
