# coding -*- coding: utf-8 -*-
"""
Django settings for prizmer project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [   
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',            
                'django.template.context_processors.request',                
            ],
        },
    },
]

STATIC_ROOT = os.path.join(BASE_DIR, "prizmer/static")
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "../prizmer/static"),    
                     os.path.join(BASE_DIR, "../prizmer/static/excel"), 
                      os.path.join(BASE_DIR, "../prizmer/static/account_prizmer_imgs"),                     
                    ) 

                    

import sys
sys.path.append(os.path.join(BASE_DIR, "static/common_sql"))
sys.path.append(os.path.join(BASE_DIR, "polling/drivers"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v&up**c2s4u=r*76o0gt0)v8#uwq2#83!l8u!*xp04kea!-$wu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'rest_framework',
#    "gunicorn",
    'general',
    'loginsys',
    'AskueReports',
   # 'AskueViz',
    'service',
    'account_prizmer',
    'polling',
    #'prizmer_api',

)

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

ROOT_URLCONF = 'prizmer.urls'

WSGI_APPLICATION = 'prizmer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.6/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.postgresql_psycopg2',
        'NAME': 'citybay',
        #'NAME': 'komunarka_k10',
        #'NAME': 'sovet',
        #'NAME': 'ryabina',
        #'NAME': 'tro_sud',
        #'NAME': 'fresh',
        # 'NAME': 'pav',
        #'NAME': 'dubi',
        #'NAME': 'ogni2',
        #'NAME': 'ogni1',
        #'NAME': 'sobytie',
        #'NAME': 'pogodinka2',
        #'NAME': 'obninsk1',
        # 'NAME': 'template',
        #'NAME': 'pogodinka2',
        # #'NAME': 'template_1501',
        #'NAME': 'sobytie',
        #'NAME': 'fresh',
        'USER': 'postgres',
        'PASSWORD': '1',
        #'HOST': 'localhost',
        'HOST': '192.168.50.49',
        #'HOST': '94.199.105.211',
        'PORT': '5432',
        #'PORT': '14012',
        'OPTIONS': {
            'client_encoding': 'UTF8',            
            }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.6/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_COOKIE_AGE = 86400

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.6/howto/static-files/



#For gunicorn correct work
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    }
    
import logging.config
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR+'\static\log\service_log.log',
        }},
    'loggers': {
        'service_log': {
            'handlers': ['file'],
            'level': os.getenv( 'DJANGO_LOG_LEVEL', 'INFO'),
         },
        }
}

CLEAN_DOUBLE_30 = False #Удаление получасовок перед формированием отчёта, актулаьно для СЭТов
SHOW_LIC_NUM = False #Показывать лицевой номер в отчёте, актуально для 91, 102, 104, 106 и старше отчётов
SEPARATOR = ',' # Какой разделитель использовать при экспорте в excel '.' or ','
ROUND_SIZE = 3 #Сколько знаков после запятой будет выводится в отчёт excel